import type { Product } from "../ui/ProductsList/ProductsList";

export const data: Product[] = [
  {
    _id: "1",
    name: "Elegant Chair",
    description: "A stylish and comfortable chair for your living room.",
    price: "120",
    images: [
      "https://example.com/image2.jpg",
      "https://example.com/image3.jpg",
    ],
    category: "Furniture",
    stock: 15,
    discount: 10,
    isAvailable: true,
    color: "White",
    countryOfOrigin: "Italy",
    material: "Wood",
    type: "Herringbone",
  },
  {
    _id: "2",
    name: "Modern Table",
    description: "A sleek and modern table for your workspace.",
    price: "250",
    images: [
      "https://example.com/table1.jpg",
      "https://example.com/table2.jpg",
    ],
    category: "Furniture",
    stock: 5,
    discount: 0,
    isAvailable: true,
    color: "Light Gray",
    countryOfOrigin: "Germany",
    material: "SPC",
    type: "Plank",
  },
  {
    _id: "3",
    name: "Cozy Sofa",
    description: "A cozy and spacious sofa for your family.",
    price: "500",
    images: [
      "https://example.com/sofa1.jpg",
      "https://example.com/sofa2.jpg",
    ],
    category: "Furniture",
    stock: 2,
    discount: 15,
    isAvailable: false,
    color: "Gray",
    countryOfOrigin: "Poland",
    material: "Wood",
    type: "Chevron",
  },
  {
    _id: "4",
    name: "Luxury Armchair",
    description: "A premium armchair for an elegant interior.",
    price: "300",
    images: [
      "https://example.com/armchair1.jpg",
      "https://example.com/armchair2.jpg",
    ],
    category: "Furniture",
    stock: 10,
    discount: 5,
    isAvailable: true,
    color: "Beige",
    countryOfOrigin: "France",
    material: "SPC",
    type: "Herringbone",
  },
  {
    _id: "5",
    name: "Wooden Desk",
    description: "A natural wooden desk for your home office.",
    price: "400",
    images: [
      "https://example.com/desk1.jpg",
      "https://example.com/desk2.jpg",
    ],
    category: "Furniture",
    stock: 7,
    discount: 10,
    isAvailable: true,
    color: "Light Brown",
    countryOfOrigin: "Sweden",
    material: "Wood",
    type: "Plank",
  },
  {
    _id: "6",
    name: "Dining Table",
    description: "A spacious table for dining with family.",
    price: "600",
    images: [
      "https://example.com/diningtable1.jpg",
      "https://example.com/diningtable2.jpg",
    ],
    category: "Furniture",
    stock: 3,
    discount: 20,
    isAvailable: false,
    color: "Brown",
    countryOfOrigin: "USA",
    material: "Wood",
    type: "Chevron",
  },
  {
    _id: "7",
    name: "Minimalist Coffee Table",
    description: "A sleek coffee table for your modern living room.",
    price: "150",
    images: [
      "https://example.com/coffeetable1.jpg",
      "https://example.com/coffeetable2.jpg",
    ],
    category: "Furniture",
    stock: 8,
    discount: 5,
    isAvailable: true,
    color: "Black",
    countryOfOrigin: "USA",
    material: "SPC",
    type: "Herringbone",
  },
    {
      _id: "8",
    name: "Sleek Side Table",
    description: "A modern side table for any space.",
    price: "100",
    images: [
      "https://example.com/sidetable1.jpg",
      "https://example.com/sidetable2.jpg",
    ],
    category: "Furniture",
    stock: 12,
    discount: 5,
    isAvailable: true,
    color: "White",
    countryOfOrigin: "Italy",
    material: "Wood",
    type: "Herringbone",
  },
  {
    _id: "9",
    name: "Wooden Bookshelf",
    description: "A stylish bookshelf for your books and decorations.",
    price: "220",
    images: [
      "https://example.com/bookshelf1.jpg",
      "https://example.com/bookshelf2.jpg",
    ],
    category: "Furniture",
    stock: 5,
    discount: 0,
    isAvailable: true,
    color: "Light Brown",
    countryOfOrigin: "Sweden",
    material: "Wood",
    type: "Plank",
  },
  {
    _id: "10",
    name: "Adjustable Office Chair",
    description: "A comfortable chair for long hours of work.",
    price: "180",
    images: [
      "https://example.com/officechair1.jpg",
      "https://example.com/officechair2.jpg",
    ],
    category: "Furniture",
    stock: 10,
    discount: 10,
    isAvailable: true,
    color: "Black",
    countryOfOrigin: "Germany",
    material: "SPC",
    type: "Plank",
  },
  {
    _id: "11",
    name: "Comfortable Lounge Chair",
    description: "A comfortable lounge chair for your relaxation.",
    price: "320",
    images: [
      "https://example.com/loungechair1.jpg",
      "https://example.com/loungechair2.jpg",
    ],
    category: "Furniture",
    stock: 6,
    discount: 15,
    isAvailable: false,
    color: "Beige",
    countryOfOrigin: "France",
    material: "SPC",
    type: "Herringbone",
  },
  {
    _id: "12",
    name: "Compact Coffee Table",
    description: "A space-saving coffee table for small living rooms.",
    price: "90",
    images: [
      "https://example.com/compacttable1.jpg",
      "https://example.com/compacttable2.jpg",
    ],
    category: "Furniture",
    stock: 14,
    discount: 5,
    isAvailable: true,
    color: "Light Gray",
    countryOfOrigin: "Germany",
    material: "SPC",
    type: "Herringbone",
  },
  {
    _id: "13",
    name: "Spacious Wardrobe",
    description: "A spacious wardrobe for your clothing storage.",
    price: "700",
    images: [
      "https://example.com/wardrobe1.jpg",
      "https://example.com/wardrobe2.jpg",
    ],
    category: "Furniture",
    stock: 3,
    discount: 20,
    isAvailable: true,
    color: "Brown",
    countryOfOrigin: "USA",
    material: "Wood",
    type: "Chevron",
  },
  {
    _id: "14",
    name: "Versatile Shelf",
    description: "A versatile shelf to organize your belongings.",
    price: "150",
    images: [
      "https://example.com/shelf1.jpg",
      "https://example.com/shelf2.jpg",
    ],
    category: "Furniture",
    stock: 7,
    discount: 0,
    isAvailable: true,
    color: "White",
    countryOfOrigin: "Italy",
    material: "Wood",
    type: "Herringbone",
  },
  {
    _id: "15",
    name: "Stylish TV Stand",
    description: "A stylish TV stand for your living room.",
    price: "250",
    images: [
      "https://example.com/tvstand1.jpg",
      "https://example.com/tvstand2.jpg",
    ],
    category: "Furniture",
    stock: 9,
    discount: 10,
    isAvailable: true,
    color: "Light Brown",
    countryOfOrigin: "Sweden",
    material: "Wood",
    type: "Plank",
  },
  {
    _id: "16",
    name: "Elegant Nightstand",
    description: "A nightstand to complement your bedroom.",
    price: "120",
    images: [
      "https://example.com/nightstand1.jpg",
      "https://example.com/nightstand2.jpg",
    ],
    category: "Furniture",
    stock: 10,
    discount: 5,
    isAvailable: true,
    color: "Black",
    countryOfOrigin: "Germany",
    material: "SPC",
    type: "Herringbone",
  },
  {
    _id: "17",
    name: "Classic Desk",
    description: "A classic desk for your home office.",
    price: "350",
    images: [
      "https://example.com/classicdesk1.jpg",
      "https://example.com/classicdesk2.jpg",
    ],
    category: "Furniture",
    stock: 4,
    discount: 0,
    isAvailable: true,
    color: "Beige",
    countryOfOrigin: "France",
    material: "SPC",
    type: "Herringbone",
  },
  {
    _id: "18",
    name: "Modern Sideboard",
    description: "A modern sideboard for your living room.",
    price: "500",
    images: [
      "https://example.com/sideboard1.jpg",
      "https://example.com/sideboard2.jpg",
    ],
    category: "Furniture",
    stock: 3,
    discount: 15,
    isAvailable: true,
    color: "Light Brown",
    countryOfOrigin: "Sweden",
    material: "Wood",
    type: "Plank",
  },
  {
    _id: "19",
    name: "Contemporary Armchair",
    description: "A contemporary armchair for your living room.",
    price: "450",
    images: [
      "https://example.com/armchair3.jpg",
      "https://example.com/armchair4.jpg",
    ],
    category: "Furniture",
    stock: 2,
    discount: 0,
    isAvailable: true,
    color: "Gray",
    countryOfOrigin: "Poland",
    material: "Wood",
    type: "Chevron",
  },
  {
    _id: "20",
    name: "Wooden Bed Frame",
    description: "A wooden bed frame to complete your bedroom.",
    price: "600",
    images: [
      "https://example.com/bedframe1.jpg",
      "https://example.com/bedframe2.jpg",
    ],
    category: "Furniture",
    stock: 1,
    discount: 20,
    isAvailable: false,
    color: "Brown",
    countryOfOrigin: "USA",
    material: "Wood",
    type: "Chevron",
  }
];
