import { Product } from "./ProductsList";

export const data: Product[] = [
    {
      productId: "1",
      name: "Elegant Chair",
      description: "A stylish and comfortable chair for your living room.",
      price: "120",
      images: [
        "https://example.com/image1.jpg",
        "https://example.com/image2.jpg",
        "https://example.com/image3.jpg",
      ],
      category: "Furniture",
      stock: 15,
      discount: 10,
      isAvailable: true,
    },
    {
      productId: "2",
      name: "Modern Table",
      description: "A sleek and modern table for your workspace.",
      price: "250",
      images: [
        "https://example.com/table1.jpg",
        "https://example.com/table2.jpg",
      ],
      category: "Furniture",
      stock: 5,
      discount: 0,
      isAvailable: true,
    },
    {
      productId: "3",
      name: "Cozy Sofa",
      description: "A cozy and spacious sofa for your family.",
      price: "500",
      images: [
        "https://example.com/sofa1.jpg",
        "https://example.com/sofa2.jpg",
      ],
      category: "Furniture",
      stock: 2,
      discount: 15,
      isAvailable: false,
    },
    {
        productId: "4",
        name: "Elegant Chair",
        description: "A stylish and comfortable chair for your living room.",
        price: "120",
        images: [
          "https://example.com/image1.jpg",
          "https://example.com/image2.jpg",
          "https://example.com/image3.jpg",
        ],
        category: "Furniture",
        stock: 15,
        discount: 10,
        isAvailable: true,
      },
      {
        productId: "5",
        name: "Modern Table",
        description: "A sleek and modern table for your workspace.",
        price: "250",
        images: [
          "https://example.com/table1.jpg",
          "https://example.com/table2.jpg",
        ],
        category: "Furniture",
        stock: 5,
        discount: 0,
        isAvailable: true,
      },
      {
        productId: "6",
        name: "Cozy Sofa",
        description: "A cozy and spacious sofa for your family.",
        price: "500",
        images: [
          "https://example.com/sofa1.jpg",
          "https://example.com/sofa2.jpg",
        ],
        category: "Furniture",
        stock: 2,
        discount: 15,
        isAvailable: false,
      },
      {
        productId: "7",
        name: "Elegant Chair",
        description: "A stylish and comfortable chair for your living room.",
        price: "120",
        images: [
          "https://example.com/image1.jpg",
          "https://example.com/image2.jpg",
          "https://example.com/image3.jpg",
        ],
        category: "Furniture",
        stock: 15,
        discount: 10,
        isAvailable: true,
      },
      {
        productId: "8",
        name: "Modern Table",
        description: "A sleek and modern table for your workspace.",
        price: "250",
        images: [
          "https://example.com/table1.jpg",
          "https://example.com/table2.jpg",
        ],
        category: "Furniture",
        stock: 5,
        discount: 0,
        isAvailable: true,
      },
      {
        productId: "9",
        name: "Cozy Sofa",
        description: "A cozy and spacious sofa for your family.",
        price: "500",
        images: [
          "https://example.com/sofa1.jpg",
          "https://example.com/sofa2.jpg",
        ],
        category: "Furniture",
        stock: 2,
        discount: 15,
        isAvailable: false,
      },
      {
        productId: "10",
        name: "Elegant Chair",
        description: "A stylish and comfortable chair for your living room.",
        price: "120",
        images: [
          "https://example.com/image1.jpg",
          "https://example.com/image2.jpg",
          "https://example.com/image3.jpg",
        ],
        category: "Furniture",
        stock: 15,
        discount: 10,
        isAvailable: true,
      },
      {
        productId: "11",
        name: "Modern Table",
        description: "A sleek and modern table for your workspace.",
        price: "250",
        images: [
          "https://example.com/table1.jpg",
          "https://example.com/table2.jpg",
        ],
        category: "Furniture",
        stock: 5,
        discount: 0,
        isAvailable: true,
      },
      {
        productId: "12",
        name: "Cozy Sofa",
        description: "A cozy and spacious sofa for your family.",
        price: "500",
        images: [
          "https://example.com/sofa1.jpg",
          "https://example.com/sofa2.jpg",
        ],
        category: "Furniture",
        stock: 2,
        discount: 15,
        isAvailable: false,
      },
      {
        productId: "13",
        name: "Elegant Chair",
        description: "A stylish and comfortable chair for your living room.",
        price: "120",
        images: [
          "https://example.com/image1.jpg",
          "https://example.com/image2.jpg",
          "https://example.com/image3.jpg",
        ],
        category: "Furniture",
        stock: 15,
        discount: 10,
        isAvailable: true,
      },
      {
        productId: "14",
        name: "Modern Table",
        description: "A sleek and modern table for your workspace.",
        price: "250",
        images: [
          "https://example.com/table1.jpg",
          "https://example.com/table2.jpg",
        ],
        category: "Furniture",
        stock: 5,
        discount: 0,
        isAvailable: true,
      },
      {
        productId: "15",
        name: "Cozy Sofa",
        description: "A cozy and spacious sofa for your family.",
        price: "500",
        images: [
          "https://example.com/sofa1.jpg",
          "https://example.com/sofa2.jpg",
        ],
        category: "Furniture",
        stock: 2,
        discount: 15,
        isAvailable: false,
      },
  ]