import { Product } from "./ProductsList";

  export const data: Product[] = [
    {
      productId: "1",
      name: "Elegant Chair",
      description: "A stylish and comfortable chair for your living room.",
      price: "120",
      images: [
        "https://example.com/image2.jpg",
        "https://example.com/image3.jpg",
      ],
      category: "Furniture",
      stock: 15,
      discount: 10,
      isAvailable: true,
      color: "White",
      countryOfOrigin: "Italy",
      material: "Wood",
      type: "Herringbone",
    },
    {
      productId: "2",
      name: "Modern Table",
      description: "A sleek and modern table for your workspace.",
      price: "250",
      images: [
        "https://example.com/table1.jpg",
        "https://example.com/table2.jpg",
      ],
      category: "Furniture",
      stock: 5,
      discount: 0,
      isAvailable: true,
      color: "Light Gray",
      countryOfOrigin: "Germany",
      material: "SPC",
      type: "Plank",
    },
    {
      productId: "3",
      name: "Cozy Sofa",
      description: "A cozy and spacious sofa for your family.",
      price: "500",
      images: [
        "https://example.com/sofa1.jpg",
        "https://example.com/sofa2.jpg",
      ],
      category: "Furniture",
      stock: 2,
      discount: 15,
      isAvailable: false,
      color: "Gray",
      countryOfOrigin: "Poland",
      material: "Wood",
      type: "Chevron",
    },
    {
      productId: "4",
      name: "Luxury Armchair",
      description: "A premium armchair for an elegant interior.",
      price: "300",
      images: [
        "https://example.com/armchair1.jpg",
        "https://example.com/armchair2.jpg",
      ],
      category: "Furniture",
      stock: 10,
      discount: 5,
      isAvailable: true,
      color: "Beige",
      countryOfOrigin: "France",
      material: "SPC",
      type: "Herringbone",
    },
    {
      productId: "5",
      name: "Wooden Desk",
      description: "A natural wooden desk for your home office.",
      price: "400",
      images: [
        "https://example.com/desk1.jpg",
        "https://example.com/desk2.jpg",
      ],
      category: "Furniture",
      stock: 7,
      discount: 10,
      isAvailable: true,
      color: "Light Brown",
      countryOfOrigin: "Sweden",
      material: "Wood",
      type: "Plank",
    },
    {
      productId: "6",
      name: "Dining Table",
      description: "A spacious table for dining with family.",
      price: "600",
      images: [
        "https://example.com/diningtable1.jpg",
        "https://example.com/diningtable2.jpg",
      ],
      category: "Furniture",
      stock: 3,
      discount: 20,
      isAvailable: false,
      color: "Brown",
      countryOfOrigin: "USA",
      material: "Wood",
      type: "Chevron",
    },
    {
      productId: "7",
      name: "Minimalist Coffee Table",
      description: "A sleek coffee table for your modern living room.",
      price: "150",
      images: [
        "https://example.com/coffeetable1.jpg",
        "https://example.com/coffeetable2.jpg",
      ],
      category: "Furniture",
      stock: 8,
      discount: 5,
      isAvailable: true,
      color: "Black",
      countryOfOrigin: "China",
      material: "SPC",
      type: "Herringbone",
    },
  ];